# Generated by Django 5.1.3 on 2024-11-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('Gardien', 'Gardien'), ('Défenseur', 'Défenseur'), ('Milieu', 'Milieu'), ('Attaquant', 'Attaquant')], max_length=10)),
            ],
        ),
    ]
