# Generated by Django 5.1.3 on 2024-11-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_joueur_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipe'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buts_equipe1', models.PositiveIntegerField()),
                ('buts_equipe2', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('equipe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='myapp.equipe')),
                ('equipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='myapp.equipe')),
            ],
        ),
    ]
